### ISSUE TITLE
 plt.imshow( , , , origin="bottom") needs to be updated .

### ISSUE THREAD

**Issue by MubasherShahzad** [kamperh/lecture_dtw_notebook#1]
Using python v3, 
Origin changes from bottom to lower
Old
plt.imshow( , , , origin="bottom")
Update
plt.imshow( origin="lower")
Reference link
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.imshow.html

**Comment by kamperh** [comment]
Thanks! I updated the notebook as suggested.
